---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-14
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
