# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-postgresql-secret
    namespace: home-automation
stringData:
    postgresql-password: Meister@241282
    postgresql-postgres-password: Meister@241282