apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:oAh7e2OARH1MWcZUSEX1nCqIYPaKRofux/v2bb55tXwCVh6tOTBISSoyMED6KguEsbOixl3S/VqBahcjbB9fuFpCj3TEjkcIgCq9uVeNzTQ4ABN1UAo9yklKdos3YRtUdJ6IlBSS2SftTiBsNCXJayJ4qSaygSbf+Jq1QIE34jyKTDtoKZOoz3iQhDd1afSlsxZTyv7DUe3+oXf5opnkOmZFjME=,iv:xfaLazCSVrwec3g3S3RdypxgKi3MTNY3neoG5+NbjE0=,tag:JbVnILzUgjYmF2tx3JY/Cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T10:15:30Z"
    mac: ENC[AES256_GCM,data:HFk5HGSbHDP0bksYBGUwq/zp8Haj07+b6WYcA5dK2cpzflonMFT40TucelpmYvRdFWVmSsS6enbWhcZJxlaheeLdBr7BlAyaSB4MFExVSEzfIqParb8wkRfDcFbqMbkBeuN8rYgMhc/dDMHZIc6nEe/qZDLOOJzj0RCHHm4Z85A=,iv:lYMH8znv902dGDWCUPbBWBJ+2IdS8EpEFlXocCVQXm8=,tag:68O9CNuS+FOJeqepC65BNw==,type:str]
    pgp:
        - created_at: "2021-11-16T10:15:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6LG/l2XwbtSAQ/6Aw2Ws5A3MvlLhTFrtjFUL9n6dEydyjOtIJG35WrOsflq
            RHpTXXjO9lC8tRPiF0RW5T0RhRFJyUmB+KoVl3QSV/QrpkVEvL2UZRMouivERhcW
            WU8VnebBxLMwJUuA1VZCk7ubcKNGx1wICiA8R3Ufd620hD1/MsmXoKVxNiu4dDBi
            iOG6Hd1DlK2P0kpJil6EnQwAYALxCXD0O7c4idRIQUpq/q9ZkNcwrJnQhlnOEncz
            HyQjyfQV+aoe47d5WdTN70qzwQqiRlWBMVphIjOBFMuvU0IoymOY2+xYaxx90svu
            ii7GCs5YiyQLbU5GOxywp5McO6AacUnSWF+eTXbqZ94p1T3u7/ydlesZbZF2tkBB
            Bj9kxnGeURacYOtl2k7kaGxwASCmOrIyW14+hFvBtdzyRuSjfKYVWSftP+J33AdI
            YFH8NnCBZitrVyrmBAwGSaejBu/NzK2xmNbtNwjHiJyanE3+dKGSblLMwt27V/s+
            VPfdKfEo4oFjEv61b7/CgkPtz45+ZsCBEqr17ii4VzUW707ViHYWWE5yXsmDqhkb
            m5PWJWwzu6hIASpx72YCNHbop2r5tXwK5rw6ZvF5OT2GJTEmlK9tAr8Ox4mexEDY
            gZHVy5fzCJZRhOPaWe7n2L53j7sPW0uqBdTA27rKsvaFfUQiyaZpGoIi4S23s5DS
            XAGeQZGuLWJ0EKTq9S6+3gbvNvacnGGJz57BE5NhVHkMklJrYZci4Fzb4CyvgcOk
            osxdaq+//7NZsqepmN6f+bMzh3kRQhgonhQhbOdKnn3ffVclJRIO9qBqC/Vj
            =5Uox
            -----END PGP MESSAGE-----
          fp: D7D53C0C8DA4FA1B26281E9FC72AD38CBC02CE98
        - created_at: "2021-11-16T10:15:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8TvLTWIOaD6AQ//XawGa/HXGpQQBdAt9nhA+rFxWYNuKAkkoYYGxI03L2Q5
            HrXDxVJ5PW2l3fM553NXZaV3V0HBeV6Pq0pilz2Azi083bjIBBnOQskwfdNBjDVJ
            wa/QR8ZFRJ0dOsi+Ug03RHqlVu0AwEXGUvKFVGCcdL0I6QIH7D+WbD5vhP2GcLYx
            N0hQsVIvPgHDFgG3mSktr80e3QguWuTtg2DNHjBzCooqVBXxLucBj1RzexA62Jl1
            OPmPZ8rwSB3cpj8+lBCRO3yuXu724AvtmnYZzt96P3EpkKipTFXuKS9WFzQq9LXF
            FhpVs6vj5RnPLv3v8JCEU9Jxax9MmeqwJ3LulaGTJZTL6PZKnExN4s0f/P8NpdPt
            F+g0nViy4u4Pyftc6l6OE7QxbOUCctzjRDlT+SZYLOYo3n7fE/JPb30RWEn967eJ
            LbMe/tTYaS/VNjZ6H8Y/66l1fuMr6hx5sis43oAwzl9hV8EIq18qE0TKMLkfWKpv
            XRSjpjA2XM8ZY86H/QjaJBvZpiEIiQxphqIqOGOTfj8u0RwHm+YVYN8lgH8/Ab6c
            xfckXPoaRGhWcpgakxOI3tNOnOuV+G766OOA/n2grgUC9nEG1xWXN0IkJGCS0V5j
            y1GD+bUsk2yYMs/S1N+RwKzUUUhhebG1jXXHj1oYUP8KgYUr7s7pq9f5vuDM9oLS
            XAHLUIaUAUGIRyBamVtaQcpJarl4Bgw170yv6r/XhfzRICZgd5HExEeG7AFXM30U
            FgJYmMm2ZvCdohZMbxuXhQcVBgIbgz2lE/xwF3P5iXKNXrEzU6T1YY/jrnai
            =0LT4
            -----END PGP MESSAGE-----
          fp: FB3777A588CAA9B5B4BCB0FC262EB4D6C32A4634
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
