---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.4
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    crds:
      enabled: true
    prometheusRule:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
#    controller:
#      tolerations:
#      - key: "arm"
#        operator: "Exists"
#    speaker:
#      tolerations:
#      - key: "arm"
#        operator: "Exists"
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
