---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsmr-reader-postgresql
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: ceph-block