kubernetes:
  children:
    master:
      hosts:
        server:
          ansible_host: 192.168.1.3
          rook_devices:
            - /dev/sdb
    worker:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.250
          rook_devices:
            - /dev/sdb
#        k8s-1:
#          ansible_host: 192.168.3.4
#          rook_devices:
#            - /dev/sdb
