---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-config
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 128Mi

  storageClassName: ceph-block