---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m

  values:
    image:
      repository: eclipse-mosquitto
      tag: 2.0.14

    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto-config
      backup.velero.io/backup-volumes: data
      pre.hook.backup.velero.io/container: fsfreeze
      pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/data"]'
      post.hook.backup.velero.io/container: fsfreeze
      post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/data"]'

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.235
        externalTrafficPolicy: Local

    auth:
      enabled: true

    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto-config

    resources:
      requests:
        memory: 32Mi
      limits:
        memory: 64Mi

    additionalContainers:
      fsfreeze:
        name: fsfreeze
        image: ghcr.io/k8s-at-home/fsfreeze:v2.37-r0
        volumeMounts:
          - name: data
            mountPath: /data
        securityContext:
          privileged: true
