kind: Secret
ansible_user: ENC[AES256_GCM,data:7SHqGw==,iv:pAwI9U/3Gf7GPPMx7YCIf6TAHf/Fa+Yp5WFrTBhRvJk=,tag:/jwcRmrB4GtoNRU7VJyfjA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0tkPwWRom8vutu5ZOgM=,iv:mMa25Ewg2SclafYQ+zEMZ1DQc+HDrKc7CZ7/dbyQxE8=,tag:Yqg5C/z0cpAjMoKmYV/+8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-27T09:18:32Z"
    mac: ENC[AES256_GCM,data:zHqqYx3xV5FqF6mwAavEnu+BA1edUSqhJ9PcHekXISUDlWfI0QNmNy+G7ts09A6u3d3PIALcsBOX9Ykvi63lcA9/b+Ca+JRx/UgFgt3rcswwT5wDpPwOUqrJVQlscDe4yLiHaka36fbWkLV7EQ9oiTxzW6aG2/Lk1+FfSM3NAyI=,iv:PRSjZbCUyArGuWPI0lInH2muSV323wxasN2ahBFYeVA=,tag:jFCPtaWMCZYRaHe3UDVOLA==,type:str]
    pgp:
        - created_at: "2021-10-27T09:18:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8TvLTWIOaD6ARAAifzy0RqzMReqNTQyBfjxIu1MNy+iQdnVRH9Q/Wwxe2Rl
            G5WYxRXF46uUTZDTCQ+tVRm7H0q9MQ+lqbIsjA93A+Y8u/A1OgAzf/Mfi5iNZutm
            noU5LlF9pabuBEjQlHPmK5QQZeh+QyJtVt7HswPjNOezs8zk4lRre1QjOm5Vwg7n
            80tGpOyHVC22LGLhJPERyA+eWB+O2+ke3HME5bmiTS+KJOS0fM+onnTCttjy1S3F
            FK7oO17ZjnWFZIf9IQW1ArbpjyCCU57cAr8I/WavFE7vP3BXiXClVgBDb+dTM4We
            eVRRMyQx5rlcDKESmjjAkDJ1YX+cm69tgqlS0RLYvII7QcoIsX5lxNev8+Pz3FIx
            auYEuEkdbYNcNvPMC9GWKhr2ifDaqv0nhCyQxhKSVLx9mRchfVgPEIQJgByepra3
            zkCcqjgBdbaUsthXWvwgwSQ+bZp6M0q60YBds7k2QG0Sv2+5WV7q8oXr26F24mck
            T7g/WkPH6apbO2s1kSVJwO1ZzgQDi02gs5Zoi9pSqdOKW6j+e0rJbRe1ui1cKKk8
            Gr2lEIBKLFYZ4P1CGJsGR3sS8fpRfJDqaKw9SRZ8iunZ/qwrJqMBChEH4iLR8SRJ
            LrtBHC5sQjrxFbveYh3fcMsy5KVfHWJh+l7thjS0nPpgkwY3nm4sfL7W18TnLpDS
            XgErPPzrfm2DCxXDJnwqcOGKZhSPOh6wmSKwqzZaPHo0NDCmIxxeMDOzASiEQcLe
            u/elNnApsjAtaD/PEgi8rym1bbXJWoQWiLDDgMpWJUWJcVQ2hh+ueklxvcffEHc=
            =bLvi
            -----END PGP MESSAGE-----
          fp: FB3777A588CAA9B5B4BCB0FC262EB4D6C32A4634
    unencrypted_regex: ^(kind)$
    version: 3.7.1
