apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:SoknlytQrAzTmHXwfwidGPKJDCtHkXRM5Gu3LFiutC2ZCobEAX6Zu0Vdse83/YahV+ta+iFp5yU9v33HET6rdeu2xfkv+YWOVnnheXgbfYPB7T1aeibKEQWVZ9DQ6m52/SfDqVWdn9Poe0Knl1SOfwqCZIgxpruwhmmy2AxH,iv:CTfXpa8F1ouWhlYP65KZVRJHByKkIlyAsH+LB3EWIEQ=,tag:5/1ohvfkrIZqzjj/bDajqg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:YDsQAsqwXBymlw==,iv:i8xRyugAgG8IgNTHXK7EPsNbV6UaehDdx0QQaQ/KBLY=,tag:82X8F6/vBVlmWfgK29i5WA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Y2SnKxjt0LMUCYrR2wMCg02cwdobClg=,iv:9AYHLhjlcsP0OKuwUGbav1hbTw2teLE9y0wzT0UE4f0=,tag:r5p0CDydlsqXmmRN8kh2Bg==,type:str]
    SECRET_TEST: ENC[AES256_GCM,data:S1xJVQ==,iv:mZSTm3FvcDlE67zsEmhKqtjFXaBNiVxHhR996DJa4to=,tag:Qzxfx4JektcN7zY3JGoDhA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:0d6AJZ3cctBM8Fx81A4=,iv:NyVcYK1KDPACbrDMIazZVXyeSoXmIsm7dN2t5BEDqe8=,tag:Jfx0GsHmn6BruVYl03yqLg==,type:str]
    SECRET_MINIO_VELERO_ACCESS_KEY: ENC[AES256_GCM,data:vSUqZg==,iv:BAOVL3Ie1ALYOUNIzvbK/837iQRpB2J/vv+qkaDLnSc=,tag:c0ff2NIuHEhm5YU27Kqg6w==,type:str]
    SECRET_MINIO_VELERO_SECRET_KEY: ENC[AES256_GCM,data:7LHoPEe7JQb69HVqg8A=,iv:GXA4uj2Ez8hE76HIYtiG/JhLD5iIVHGEbD0a3QdnPrc=,tag:+LnVNnY4VeI/cnHT91OJSA==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:5oGXSQ==,iv:QKxXoGQlaQTJgdsHjqMHeOMqyrpDTQbvijkSSFqwQl4=,tag:2aO3K9/BB5NanOOyWU/lIw==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:XSy7eM666Xt0deEXpbI=,iv:Jp9CDcxVrFuYWHOybh3ruBlYzas8JAl0aei+UU8R6ik=,tag:m3Fae4v1ueACBWJvke6geg==,type:str]
    SECRET_EMQX_USER_USERNAME: ENC[AES256_GCM,data:xCilQQ==,iv:axRavWw15EQvcDjtTbRh1WcAFyTYCPuja4axRWDxMcg=,tag:gdnAZS0KmNCTjTymHb5Otw==,type:str]
    SECRET_EMQX_USER_PASSWORD: ENC[AES256_GCM,data:/LtQEQeSIFLa0C/IuHg=,iv:DdwJPMgmzjP88+Qv4X58jbD9H1vRREeRMKWGvGi415c=,tag:VtX0uqJNRPyvl1vFQqmkGA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:mLoGaA==,iv:/eBVFmmszAyRkR1cPuPTnboMIYx7y/BZ9yyq407j3hk=,tag:gGumuM0a7X0ZBh9omrF5GA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:sMMnJdwbeQhc/KYWeAQ=,iv:HY3NG1ZPdLnHZkxqy5p8JnXzEJRyYFyZAWUE47+g22I=,tag:chrsqsxDjf6e9EdqtM/ERA==,type:str]
    SECRET_EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:pIkdv4r/ufN9E8kHfzU=,iv:kw5Dr93RkCsOY4I4n6DAKoYvY8bXi69TOXlHdTlXd+M=,tag:eRyP9AebDlF3OaFJEJMSeA==,type:str]
    SECRET_POSTGRES_USERNAME: ENC[AES256_GCM,data:sPbao8pMRpQ=,iv:28efeXFBFagUJ2qpqm9z9Q8pGkavSZYqG66ivbYBlTI=,tag:E2cksc5qXhEu8Q5Th74J8w==,type:str]
    SECRET_POSTGRES_PASSWORD: ENC[AES256_GCM,data:A5BgKBJyKqkQtEN0wl8=,iv:jaJiHcY0GKRcS1v0vrffBn5eETTg1/6cUcifEUHexck=,tag:rhicNf4cjqtbWh5cCpLhcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-18T10:58:16Z"
    mac: ENC[AES256_GCM,data:n+oVfHWXlBFD/FPp4maxYd8W4E0DNyZ3RR9IUpc9OH8PYOCpXx+WbPRYwz950mBSZ3RSU7WilAhRIcUZJhV/wP8QW60quNp71SooJmjMIxbMoHY5B1RdSgtnN+L6cseNdzc4YApgRANyPn3xBz4grct/kdf8toNcQAsV0EHDXuM=,iv:4eSK0QA0tHVWS2weoCUkrQAhxISh0P2frel+mM7JmEk=,tag:qe1BPVPwk8qzvW6Wq7p6VQ==,type:str]
    pgp:
        - created_at: "2021-11-18T10:58:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6LG/l2XwbtSARAAmBT73GMoJQvjK+vbSUcvTbEDegxQZTY9wkMHiyK8bbvz
            moSZda/kITOfuH/H7mlo+iD8lCW52GE1bpcUnFwFgmIspwPTfDKk1HcI4D+wgCuB
            o/UlKFxml92ahsnKfvwl+ZG3ye+YGkD0eOEhJJ23FPFfAeXHy5rWCUF9J+FnQXkY
            lY87zuZbfjyH5JUmIoXJ1dVaaCM6CiIWSGSmWOB59eQUOXD7zdfh71jiNfM+B7se
            J+EMpiunmHq/jO/fPW5QOcXJzDfzRHKGol11RixjqWOvdajeXFxqxhpBgtAd7MKJ
            CgKtmgMI35YP9DzeeFv6KFmQ38QDXEpGy7/qYSqp08Q7EoAGN6dwez5xOnyNcAnU
            YjbP1UqyUAZ5cSszf5/Kr8/lNrc7ZSX0gGWtHixTGO07viPTxidAAnALWhUpDRrJ
            M3IyxUYC3bOc9eXU1eKwODzKDBOZJ/QhzXQ1jkpkkfZQ0VDeeIH16/3Mgq8Vsmys
            Q4uNWt5j7RqyItcEAEv4UmDrC5E3M8unhaV7CgZCdx2PrurhRGk9S//j+gaIvKtD
            pjJN6OXGcOjvbjvLw+85d6PGuRLuYVxKbJnUVQQ+GS4Yq2BH7XyEwdlORd13+tIu
            LbEHy33bH0yisUqCGOpoNbLUn0v5Qi+ExNv7iCaIdyWq8AckSs5mmoE02iM7H4/S
            XgGHRRH6kNk42rvzL8DiA+9nHfxvElIqd1//HyixYsAxuYh6CVxAbD9IymAxjwlN
            jS+1OPImIDq1mJgzNSaRsVNu82q1dAwvm7RSLLLkVXF5M7vBVZ1vKpFAUZe4LwM=
            =O0zT
            -----END PGP MESSAGE-----
          fp: D7D53C0C8DA4FA1B26281E9FC72AD38CBC02CE98
        - created_at: "2021-11-18T10:58:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8TvLTWIOaD6AQ//WCZ/GacipRrXBwybRbsFyN/m3RxMl0YeXeQiqHp/cbZP
            CElfJOMq5e6rJlqplNn0sjCR9Q9gPsv6sJR+dZtSv7tU+I5dt3xEQ66SimuB/oHA
            8n7WfdIfR8tnqW0NJf5f3bspjkeD+kjd65Nr8pMgrOUuifHQXUz2oQNZI6YG86dt
            rhUgyIZjCqwT2Y/hhhkRSgatdSsnaQpPpXXg2stOnLdlVJltSwDeNcoRHR2dYtAm
            QgyFSBcyVuIvOtejPTvv1nnsl7FSizjvZBNjwKvXwisXZOTzH0o+T6fzD99lLq6D
            6ElYYhoN9MuPUu7lx5M/geSs/leuGXxZP7d4z/XZsXZiDlwUM2FmvbvzGRJwpK5v
            oENr9oZF/iHOPFyXS+Vn1fs7Wu6NqweHpVHc+4kENKXzL1ZDB+RqjTto0SlnVl73
            Ct58ywK1z8Dp2O25p8wfQnHC893cmZsl5w6oGYVdGe4uiFBONGarUdM2heqEhZYS
            gsr223hlmsLvReMmo8lznM5eEByzKOmc2QFWcz04/+dz5j/GufcvSkfI1G5BSZFI
            Q1nwdNuCmGVrO5eshiHmOpL6hJCuO/AW26XvEm6DXRSwKEWXNJ3rPTYWTQmaYlgn
            7nq9MtBO9+SRgmFCzLE9qlc4zC215N3l+yXHAdQULCHX46zswoY/1puSAlz+NLrS
            XgG4WFtdc47fI+/LgXL+uy4l6f7g/wXYQOzV1JmQiDUsi3BAlqa10YD0NsZFnq65
            cqhTZr52NiRgCyTfcHnEjidWjMDI4tNlLtx9ziW/mD1Q67Z9CKsEtLraesxeoag=
            =E/eU
            -----END PGP MESSAGE-----
          fp: FB3777A588CAA9B5B4BCB0FC262EB4D6C32A4634
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
