apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:t2tyWgvkaHPtj9xio3Hu2I2sQ2LLTfN1LUWGbc0gGud2HZn8xfnP5JZ9lzdZnX5WGA3d4Yyv9vcqSse4zmgBLSy7Ok5Y72zSellX8c6K08mlS8PMisBx/Q7Nhnot2errhp52XYW7il2Igzaj8gkR66W6xsnAz5Gy,iv:eR4rG+bnf5kRzUyUSTEGA57nMYVjDE7HQg3332l0jcY=,tag:+1kPVnxuNH3VKPWCNz9GkQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:cKjqTDYrDh7LQA==,iv:O3f0xvC4gZ8ErB5K/4+uHmK/gdd1ALmRWX4x3MwPrFo=,tag:rw+NxsQ5e6x2uLSeeZYLvA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:X7Krlp8rtNFjGAVJ29oWEoSF+7bp1gY=,iv:SQOBT1LqrRN2dXcZVOTQdPWHAl2nhS4AH5yGrXrAWzU=,tag:QJb3x4LllC8AsKSWMaaywg==,type:str]
    SECRET_TEST: ENC[AES256_GCM,data:x+CQ+Q==,iv:jz1veZWefWtCPCP8vix+9Jerq5ZZ5uTdErzlutyj2/U=,tag:LVLORDvaiYnAiysOGcj2Qw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:eX9xVHfliTDoQ7wPrQQ=,iv:jCKiUwZF4iORT/cs6d78E103KwX+SiTXIuU52JQR4yM=,tag:gX7sy737UzD2DlRKzPXBjw==,type:str]
    SECRET_MINIO_VELERO_ACCESS_KEY: ENC[AES256_GCM,data:gqSCTQ==,iv:vzj4mEap1wbBCwxZV4dV3u+4Ifzzs4nMelG75Q8wuC0=,tag:NkQKlmpzHcDwTSQBHeCGxw==,type:str]
    SECRET_MINIO_VELERO_SECRET_KEY: ENC[AES256_GCM,data:oGt4e9Jm7ESZT4M6dCY=,iv:wNcvtiEke7TdaMdmLqRJateQTGx6p6w9N26qh0C6b0k=,tag:BdMzI1JYBQ33nzlCqj43zw==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:RpVXhw==,iv:btSUtIWeskJf4Cc8TJDzNcrOZjmyUoelp52ZMl/Opfk=,tag:DLW/POC4Z84yvClcaBnJjA==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:+bAo6SEhZ8MV3spQa+c=,iv:lE7Hc3VRaVGm9HONgsbJZ9HCUYzkafv5whyWzoGwY8Y=,tag:1lroTK2QpAUEGTbgPX8zxQ==,type:str]
    SECRET_EMQX_USER_USERNAME: ENC[AES256_GCM,data:kJgopA==,iv:y6L3ERxb7Vq3oQumlQVeQUkw53qSap6J0Mt0CL1W6k0=,tag:wgvm7MJI40ZN8rD2jVaBeg==,type:str]
    SECRET_EMQX_USER_PASSWORD: ENC[AES256_GCM,data:ehU8SJ6p+MLkGjbVIuA=,iv:aRoPAwJg+iGHRHUgf95J0EbYa7A0MN3Sbl/xxY2jz1I=,tag:BOpZ0dKK6xjJLrMzxGLEcQ==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:xTmjXg==,iv:UtvTZ5NCmr/kRybEUERhW0OQFq3n3QXXIJi24//L3RU=,tag:/kRsIKQutL1WcvxLQA9ZmA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:5L7WfbHZegSUAqiKkLU=,iv:W42z3I2bqN+mZ8ayllGta0YxhQvl9mgeM01Ma8cWc38=,tag:PT3ZDBXBvbYUqMWLVDVd3Q==,type:str]
    SECRET_EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:WlUR8kq7zAmqWQsea18=,iv:KddPQBnnzVXU4uupLD6CBeJw0ZECJewldFDzgGMmVE8=,tag:A/iJLKjlwVHlEHny/29UpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T10:15:57Z"
    mac: ENC[AES256_GCM,data:K1cFziXIQEwD+XbaJv8yGx6fXTwGLtzknldK+ZlKvm2D4xINiuUreKysP0p08Ut+h8xwVVvbQS2dfKW7mRMzu1L/XUV6ASF4TjVaIVc1N4hZPGolrQ7ugkAmGU6rj4zvtU+Bvg2zBpLunRq6e2Z9Yw8/7ARgh4lR8Bp0bopI8cg=,iv:tjBc5xVpHqme0TK2+sOOQI2ut1RUZClowW+HBy3J8vQ=,tag:PiNhwSC9Zwy4YSp9pCkalg==,type:str]
    pgp:
        - created_at: "2021-11-16T10:15:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6LG/l2XwbtSARAApPBcT5Cdyy+//zLb74XWi4Jlxi7JjikuWs9hbiocOeFF
            EZBHErweqEUXDVVHoujEsgxfGy3ivjqnYTb3g0/+zx4AlRpaA6Z9Gch9X2wlywfX
            3Gaj17uKezeLdH7BlKILUoGgk16aBEUa/xBJmOqsForKKZBzTao7HL2XzA1CPv1V
            +3U+EwK7RcNYIddY6GDqJAQYp+zgFLeZJIy6a0S1SVIQM7Pyq7PRhIVBkD7xhSjN
            4KaIoUffXs/zIArRyj9MTLeJWz7kSZR5Z8Va2nQpEeRHrf/ESmvCGoHt9cMKwSHE
            r9QIhI7ZqypOsVwhKruVQ/kMtuQt3YI25krtK9NAlPThti19mNIAhz2E/KZEt7ed
            c2Lv+boJvUNJ0NFqnMml4TFACE0qJP3+bd5UpcUXQFU0HigWTS/xyuQj8iLhjGxS
            RJiUjjBrB6qE13b5m/YEgMQCTLqhdgmhil9Rx3NLiXke3bzsuWOLQk47c7USpZFX
            5alyNlMAzo8mNyiaWsv5zz77SciwEKEJ/P8Z8r8ivHo4BIlb1Z2tmQuV/e1Fob9h
            UO4dbwylGdYjirNrnTWIXR2UNq9zlFWSNeACRtXJxRmqx2PWqUEmnRbxH3idHVvq
            jiDZtlGRCmpNlwmjskSHOSdffcT0sP7Bocq+4qDvUYdgmR2pErq8gYS3SXovYrDS
            XgEXbujNU0dlbYQI0F52+IeYs3c0lmFGhqAehcLW6CqmPZHc017gHG9Ig7jbJWwe
            k1mzS4cjP7zfFoZdvRwSyX7Sku5joNLQ4lTtwAo27TIqD2ovstuAur86feS/NM0=
            =4Bej
            -----END PGP MESSAGE-----
          fp: D7D53C0C8DA4FA1B26281E9FC72AD38CBC02CE98
        - created_at: "2021-11-16T10:15:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8TvLTWIOaD6AQ/+JHNH9ugMLBUhdoCkK9yY+iHmw825U706MMg/wKGz2l+l
            +uH04FZTXb8gvYSCjW62pOWGt9UVdlvThfb5D+y1ahKt3bCJw1NZprgxYLNCwI1g
            nt+Uxg5iiwhAwmy4zDR214q+19iRDOCAuMbnX6a5FrW70RyHCMar/L6IeJDhnVGr
            /SQfyWW/Js6MKKGZHCCPjIur/FbRuKrQnsS4HiyLYsfDBNrzjxtQDoOSXrOz9dZ1
            HQsVUnuHGBHyI5/MBpaFXAD3emgkJlDbCNA6bxJnnTUEDXinuYdQNkO1bwVEBTHG
            5/EzMtGw4ZrwL9S3DWuCUDuxz3FhkJYtPXpD6gxHESyU9DGIb2kMeVrqHS7HIzIi
            DQ+HZ1gKH5QTnIxeXuXgOXeSn/DncVW/AU7EWF0bgR3iCy3dcU//pEUmtu/UWG5K
            IP3xC9merCQqQpuwGIgZPoayN30iTg5QeqQZuB47YxjYhT8XWJ6Q0QNl9WH4XeAd
            0zludT95awNgenlqosbcKiezn8pj7VdcrS4MSSCqDKw75Xw11kJs02NqSNz+zW9t
            MEoPpbN6lviwYrLMK71AFEfc2DrRD7ZoDoLkj4cXYKymyH+5ZWSf+OU47oe9ydV1
            pBMH5vCZYC33uYYo5HQXKZUoLuLhOIY2urg4xjK+htfDjPDpbzh412FyIL85aCjS
            XgEgYHzX8TMYtPWmypJRuQqhA+hkyOd7Uyqtgt9ITljDd+BZ2TcL0aFztzrJWmtn
            K7Zt9L7VDydVlrSKuSlYInzqbBvKnzrO7SbfzsXN283cD+NiC+TCDhe99r3Dn34=
            =770U
            -----END PGP MESSAGE-----
          fp: FB3777A588CAA9B5B4BCB0FC262EB4D6C32A4634
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
