---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.1.231-192.168.1.240
  METALLB_TRAEFIK_ADDR: 192.168.1.230
  #
  SVC_HOME_ASSISTANT_ADDR: "192.168.1.233"
  SVC_EMQX_ADDR: "192.168.1.232"
