---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-v1
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block