---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.9.13
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    image:
      repository: bitnami/postgresql
      tag: 14.5.0
    postgresqlUsername: ${SECRET_POSTGRES_USERNAME}
    postgresqlPassword: ${SECRET_POSTGRES_PASSWORD}
    persistence:
      enabled: true
      existingClaim: postgresql-data-v1
    primary:
      podAnnotations:
        backup.velero.io/backup-volumes: data
        pre.hook.backup.velero.io/container: fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/bitnami/postgresql"]'
        post.hook.backup.velero.io/container: fsfreeze
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/bitnami/postgresql"]'
      sidecars:
        - name: fsfreeze
          image: ghcr.io/k8s-at-home/fsfreeze:v2.37-r0
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
          securityContext:
            privileged: true
