apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database
  - flux-system
  - home
  - kube-system
  - networking
  - monitoring
  - system-upgrade
  - home-automation
  - velero
