# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:O6gft4jBdIPxzWzh/yDdZXhLwHoUuuct6awmxrGEpHAaSC95loHuNw==,iv:0BdJ1LtYDAgsHdL7I4jsY6ICPY855lnyG5dn25nc8qk=,tag:plL+HwOGGUSMNKahy4QJBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T15:10:40Z"
    mac: ENC[AES256_GCM,data:VlZDMboPbt+tAa8Wm9F65mUcwJA7p/m50kbVMOgaqj7J6YBHaOJxBW+KC2LioASCeeLalxUwFMeSKmxlJaFmVfROguJu4BUqVexB6Ol1zhHYO51q0c1DxZgPNqd81qvQCvi+M7GrbjJZvZYAwkCJD0BM4VSVZuDApjSEirPFXRo=,iv:6mri0uX53grIGS4mJTgQL/07gy/+HXHgpenpo3YZzPE=,tag:SHEcVc5ahQsbYJpnDNQLmw==,type:str]
    pgp:
        - created_at: "2021-11-16T15:10:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6LG/l2XwbtSARAArIUgKhPekOcHAih1MK5tnFiHjaU412xmvU7DICBN536u
            0NQJ2eb79En2yoQZutd94yTsS0l5ehyY//gKpTwBAZWugXQNRiJ+8jSckhNqaE61
            JTqlVERmfYTHegFxQMAFngNHseO4Qs7W+cj1XhqQbubGRFBCJ4u+u3cl6mG9rVM1
            vo0CRjwKYV5mbrHq4bxIvsRLTfUla+jXbHcAU6XIymBDuNHLEwAu/adZJ0MlYxt4
            fje72l+o7kCqUkbTkxACVXERCHXXSxJnp2XsgqjuHrFrTY41PnJh7AlKI75O8Zea
            Fl1J5O+1/9pG2+9o55fv9aSy/TfNhRdur5hnMw6zxlUXtRY/Q12IQXM9CbO5Z3Yw
            uum05tE2P++9m1b8iogq/7je7FCL/1TH70+HtnzG/mD7zfmu4n/1vWEdzVGqbe7z
            woGsI9lLLcXRYT7OblvtpqvZxtA9zpp2FGX5N5xkgGkTeTiV/PRqvG8rXNDd3fhz
            fcv5D8iIyxFQRFkOQexDGmjYlXd3HSCR9fbhS/XlBZwzMJWPXU4TxkIhAQnP/qwF
            iYVafYLtkbmMdy10yV9lcuj4RcMlzViqfjYPsoZvFSbwJalnAtSxJ7RRbmEZOdrb
            pq7KROM5V/N0As1oTa5x8/M+O+Z14NKyYfyqpyZgUkHKOkauY1rFt+y+BllHJM7S
            XgGRn2Z2UvPf5dm6QOeFt+kjcSwWWmPKAP6jItOzyXTHML17z5UJItuorNGHP97R
            doImHpFynLIVFbl9C09o2myeJLfPx3V99pRrHIwNHqCtdD2eI9iOBNlv4PAiY4k=
            =HJ7V
            -----END PGP MESSAGE-----
          fp: D7D53C0C8DA4FA1B26281E9FC72AD38CBC02CE98
        - created_at: "2021-11-16T15:10:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8TvLTWIOaD6AQ/+KxcHcZXwa1ko8Jg3lb0EH1uykQQnM/hjPyPqqgHO2oe9
            TfmZ4/6BKNfaCfF0FOcJxiHR+S8zrX/Z8St2pM0Y8lqohLT4nARDB/i2e3HsvWdg
            GabbW0C54z6RxQjOPRINMNQJSPR58muINwQIVJiRGtaOtglmc9D9OYvMZa5IPCqz
            YzLRcjaTyfy2S0GQIPTbKmeojgW/V+FsP2WiHtJ2TH/Hst5+xYqVEEV7IW7f+vd/
            ZVFKjqyBGUHMKSgFrDH168dKLi/kQS1cgyp5ngspC9z65MK7mh3RTslugPSENh2t
            E6JRT8v16V0QOqI5fnpsteRXYFtHmmZeChtIQYK32kAjsnz+vuOVpnRVBeAvvD2y
            fkCbPNLCqPZdSt6FR3kh9r+WLAkq1HIcvsa0wjv0eLVgjL9qhMJGRi3zYjQxJ5tj
            0jZh37Eyu1YHM9YzWBo9NVrEpa2hXoKZWmIy1swr9F8463DSxR4PadAN27YOMkI1
            CPE+NqIC2WV4sc8CiOS2gvmcWoRjFpzoAoCyFPKZatgZPSe0Dn/msa/9YFuImVLD
            Y2CmXYbbxDr+if5DE1JWvJef/sltRvtvUurNC9bo+4Bsft2TQKAiokZJcH5vbJFV
            gFx3UCv/bKM1+eqEgtyoQY6JjsTnAWjrt0vurtU1Rp3JqQckLFDDLYm1glGNpKfS
            XgHNivjLsZEEQDJbDLDM5hpegOGODWjo+uob0tuO1VX2NV0AtemhrxpX/ir3+Zpt
            5kMiBDIYiCgf1x2kgVbiNvT6kzyCP0/tKed/8u0G/Lj8aF2bwXj5ga3T0d95pdM=
            =px26
            -----END PGP MESSAGE-----
          fp: FB3777A588CAA9B5B4BCB0FC262EB4D6C32A4634
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
