---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.12.0
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph
  values:
    toolbox:
      enabled: true
    monitoring:
      enabled: true
    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      dashboard:
        enabled: true
        urlPrefix: /
      mon:
        count: 3
        allowMultiplePerNode: true
      mgr:
        count: 1
        modules:
          - name: pg_autoscaler
            enabled: true
    ingress:
      dashboard:
        annotations:
          kubernetes.io/ingress.class: "traefik"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
          hajimari.io/enable: "true"
          hajimari.io/icon: "server"
        host:
          name: "rook.${SECRET_DOMAIN}"
          path: "/"
        tls:
          - hosts:
              - "rook.${SECRET_DOMAIN}"
            secretName: "rook-tls"
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
          - name: "k8s-0"
            devices:
              - name: "sdb"
          - name: "server"
            devices:
              - name: "sdb"
          - name: "k8s-1"
            devices:
              - name: "sda"
    cephFileSystems: []
    cephObjectStores: []
